name: Deploy to VMware VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Test connection
        run: ssh -o StrictHostKeyChecking=no nishan@192.168.145.129

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 192.168.145.129
          username: nishan
          key: -----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABAuT33B74
uiINXENqA6Wm8QAAAAGAAAAAEAAAAzAAAAC3NzaC1lZDI1NTE5AAAAIBhAF6RbbPQrlSl6
jd+/BxKnYtw5PzSIlB9Hy/rJtxK9AAAAoP/9lYsiS0yFLvNDs2FWxgs0GPPNxX8d51V7F6
9Fe9J2v3ShifLNz6IBkpHn5jZsp5qzP6xlNIk5JukTLLeYAvU+tkhjIl53MQ1/IqlRyiX1
a0Bf3/kLHd89vlTU+L0oRNo4bsiRfzQbubkUdyzKojve/mKzi0z0GxmCBR/JJn9yxkCAEQ
SgqKtal7AVH7dBIZNMLhrVljxAR97ol/VBIYk=
-----END OPENSSH PRIVATE KEY-----

          script: |
            cd /var/www/html/devops-test  # Change to your project path
            git pull origin main
            composer install --no-dev --optimize-autoloader
            php artisan migrate --force
            php artisan cache:clear
            php artisan config:clear
            systemctl restart apache2
