name: Deploy to VMware VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Test connection
        run: ping -c 4 192.168.145.129

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 192.168.145.129
          username: nishan
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          script: |
            cd /var/www/html/devops-test  # Change to your project path
            git pull origin main
            composer install --no-dev --optimize-autoloader
            php artisan migrate --force
            php artisan cache:clear
            php artisan config:clear
            systemctl restart apache2
