
name: Deploy to VMware VM

on:

  push:

    branches:

      - main

jobs:

  deploy:

    runs-on: ubuntu-latest

 

    steps:

      - name: Checkout Code

        uses: actions/checkout@v3

 

      - name: Deploy via SSH

        uses: appleboy/ssh-action@v0.1.7

        with:

          host: 192.168.145.129

          username: nishan

          key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBhAF6RbbPQrlSl6jd+/BxKnYtw5PzSIlB9Hy/rJtxK9 nissandhakal11@gmail.com

          script: |

            cd /var/www/html/devops-test  # Change to your project path

            git pull origin main

            composer install --no-dev --optimize-autoloader

            php artisan migrate --force

            php artisan cache:clear

            php artisan config:clear

            systemctl restart apache2